apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: 13.37.32.105:8085/repository/ak-docker-repo/sample
  imagePullSecrets:
  - name: regcred
