apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: 13.37.32.105:8085/sample
    imagePullPolicy: Always
  imagePullSecrets:
  - name: regcred
